name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit ID and lowercase repository name
        id: vars
        run: |
          echo "commit_id=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "repository_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.repository_lowercase }}:latest .
          docker tag ghcr.io/${{ env.repository_lowercase }}:latest ghcr.io/${{ env.repository_lowercase }}:${{ env.commit_id }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.repository_lowercase }}:latest
          docker push ghcr.io/${{ env.repository_lowercase }}:${{ env.commit_id }}
